<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-HTVADQ6" name="com.testngconcepts.com.TestNGExceptionsConcept" tests="3" failures="0" timestamp="10 Jul 2020 16:59:58 GMT" time="0.015" errors="0">
  <testcase name="exceptionConcept" time="0.015" classname="com.testngconcepts.com.TestNGExceptionsConcept"/>
  <testcase name="arithmaticException" classname="com.testngconcepts.com.TestNGExceptionsConcept">
    <skipped/>
  </testcase> <!-- arithmaticException -->
  <testcase name="nullPointerException" classname="com.testngconcepts.com.TestNGExceptionsConcept">
    <skipped/>
  </testcase> <!-- nullPointerException -->
</testsuite> <!-- com.testngconcepts.com.TestNGExceptionsConcept -->
